[network]
name = 'PointNet'

[layer1]
type = 'tnet'
format = 'point' #'point'/'feature'

[layer2]
type = 'conv2d'
name = 'conv1'
output_channel = 64
stride = 1
fileter_size = [3,1]
padding = 'VALID'
bn=true
activation_fn = 'ReLU'

[layer3]
type = 'conv2d'
name = 'conv2'
output_channel = 64
stride = 1
fileter_size = [1,1]
padding = 'VALID'
bn=true
activation_fn = 'ReLU'

[layer4]
type = 'tnet'
format = 'feature' #'point'/'feature'

[layer5]
type = 'conv2d'
name = 'conv3'
output_channel = 64
stride = 1
fileter_size = [1,1]
padding = 'VALID'
bn=true
activation_fn = 'ReLU'

[layer6]
type = 'conv2d'
name = 'conv4'
output_channel = 128
stride = 1
fileter_size = [1,1]
padding = 'VALID'
bn=true
activation_fn = 'ReLU'

[layer7]
type = 'conv2d'
name = 'conv5'
output_channel = 1024
stride = 1
fileter_size = [1,1]
padding = 'VALID'
bn=true
activation_fn = 'ReLU'

[layer8]
type = 'maxpool'
karnel_size = [1,64,1,1] #num points
stride = [1,2,2,1]
padding = 'VALID'

[layer9]
type = 'reshape'
shape = [100, -1]  #batch_size

[layer10]
type = 'fc'
name = 'fc1'
output_channel = 512
bn=true
activation_fn = 'ReLU'
dropout = true
drate = 0.7

[layer11]
type = 'fc'
name = 'fc2'
output_channel = 256
bn=true
activation_fn = 'ReLU'
dropout = true
drate = 0.7

[layer12]
type = 'fc'
name = 'fc3'
output_channel = 1 #output_class
bn=false
activation_fn = 'None'
dropout=false
drate = 0